name: reviewdog
on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  eslint:
    if: github.event.pull_request.draft == false
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: './**/*.{ts,tsx}' 
      - name: eslint
        run: yarn lint
