name: frontend-reviewdog
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
    - "client/**/*.{ts,tsx,css}"
    - ".github/workflows/reviewdog.yml"

jobs:
  eslint:
    if: github.event.pull_request.draft == false
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: reviewdog-eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,tsx}' 
          fail_on_error: true
          workdir: ./client

      - name: reviewdog-stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_input: './**/*.{ts,tsx,css}'
          fail_on_error: true
          workdir: ./client
